VOXELFEATURE:
    fmriprep_name: fMRIPrep
    bold_suffix: bold
    confound_suffix: regressors
    mask_threshold: 2.58
    zoom: !!python/tuple
    - 2
    - 2
    - 2
    confounds: null
    smoothing_fwhm: 6
    standardize: true
    high_pass: 0.0078
    detrend: false
    n_thread: 4
LATENTPROCESS:
    hrf_model: glover
    use_duration: false
    n_core: 4
    onset_name: onset
    duration_name: duration
    end_name: null
    use_1sec_duration: true
HBAYESDM: {}
LOADER:
    reconstruct: false
    normalizer: none
    scale:
    - -1
    - 1
    verbose: 1
MVPA:
    elasticnet:
        alpha: 0.001
        n_samples: 30000
        shuffle: true
        max_lambda: 10
        min_lambda_ratio: 0.0001
        lambda_search_num: 100
        n_jobs: 16
        n_splits: 5
    mlp:
        layer_dims:
        - 1024
        - 1024
        activation: linear
        activation_output: linear
        dropout_rate: 0.5
        val_ratio: 0.2
        optimizer: adam
        learning_rate: 0.001
        loss: mse
        n_epoch: 50
        n_patience: 10
        n_batch: 64
        n_sample: 30000
        use_bias: true
        use_bipolar_balancing: false
    cnn:
        layer_dims:
        - 8
        - 16
        - 32
        kernel_size:
        - 3
        - 3
        - 3
        logit_layer: 256
        activation: relu
        activation_output: linear
        dropout_rate: 0.2
        val_ratio: 0.2
        optimizer: adam
        loss: mse
        learning_rate: 0.001
        n_epoch: 50
        n_patience: 10
        n_batch: 64
        n_sample: 30000
        batch_norm: true
        use_bipolar_balancing: false
MVPACV:
    method: 5-fold
    n_cv_repeat: 1
    cv_save: true
MVPAREPORT:
    elasticnet:
        confidence_interval: 0.99
        n_coef_plot: 150
        map_type: z
        sigma: 1
    mlp:
        map_type: z
        sigma: 1
    cnn:
        map_type: z
        sigma: 1
